---
title: "'On Error' ステートメントは、'Using' ステートメント内では使用できません"
ms.date: 07/20/2015
f1_keywords:
- vbc36013
- bc36013
helpviewer_keywords:
- BC36013
ms.assetid: 5b399bf9-6595-46e0-a808-378f6c28568b
ms.openlocfilehash: 4134550e07528d39055b061417cb377bbd04f978
ms.sourcegitcommit: bf5c5850654187705bc94cc40ebfb62fe346ab02
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 09/23/2020
ms.locfileid: "91092251"
---
# <a name="on-error-statements-are-not-valid-within-using-statements"></a>'On Error' ステートメントは、'Using' ステートメント内では使用できません

`On Error` ステートメントが `Using` ステートメント内で使用されていますが、このコンテキストには使用できません。  
  
 **エラー ID:** BC36013  
  
## <a name="to-correct-this-error"></a>このエラーを解決するには  
  
- `Try…Catch` ブロックなどの構造化エラー処理を `On Error` ステートメントの代わりに使用します。  
  
## <a name="see-also"></a>関連項目

- [On Error ステートメント](../language-reference/statements/on-error-statement.md)
- [Try ブロックと Catch ブロックを使用して例外をキャッチする方法](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Try...Catch...Finally ステートメント](../language-reference/statements/try-catch-finally-statement.md)
