---
title: "'On Error' ステートメントは、'Using' ステートメント内では使用できません"
ms.date: 07/20/2015
f1_keywords:
- vbc36013
- bc36013
helpviewer_keywords:
- BC36013
ms.assetid: 5b399bf9-6595-46e0-a808-378f6c28568b
ms.openlocfilehash: 5810ed72cd41411260be34993728af96fedcd8f8
ms.sourcegitcommit: 2701302a99cafbe0d86d53d540eb0fa7e9b46b36
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 04/28/2019
ms.locfileid: "64633534"
---
# <a name="on-error-statements-are-not-valid-within-using-statements"></a>'On Error' ステートメントは、'Using' ステートメント内では使用できません
`On Error` ステートメントが `Using` ステートメント内で使用されていますが、このコンテキストには使用できません。  
  
 **エラー ID:** BC36013  
  
## <a name="to-correct-this-error"></a>このエラーを解決するには  
  
- `Try…Catch` ブロックなどの構造化エラー処理を `On Error` ステートメントの代わりに使用します。  
  
## <a name="see-also"></a>関連項目

- [On Error ステートメント](../../visual-basic/language-reference/statements/on-error-statement.md)
- [例外をキャッチする try/catch ブロックを使用する方法](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Try...Catch...Finally ステートメント](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
