---
title: "'Catch' ブロックに到達しませんでした。'<exception>' は、同じ Try ステートメントで処理しました。"
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: 987a509b4b099a0a1f728f55dfb2b35a8770af3f
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 06/04/2020
ms.locfileid: "84395481"
---
# <a name="catch-block-never-reached-exception-handled-above-in-the-same-try-statement"></a><span data-ttu-id="319c8-102">'Catch' ブロックに到達しませんでした。'\<exception>' は、同じ Try ステートメントで処理しました。</span><span class="sxs-lookup"><span data-stu-id="319c8-102">'Catch' block never reached; \<exception> handled above in the same 'Try' statement</span></span>
<span data-ttu-id="319c8-103">先行する `Catch` ブロックで処理されるため、コードの `Try` ブロックには到達できません。</span><span class="sxs-lookup"><span data-stu-id="319c8-103">A `Catch` block in the code cannot be reached because it is handled in a preceding `Try` block.</span></span>  
  
<span data-ttu-id="319c8-104">既定では、このメッセージは警告です。</span><span class="sxs-lookup"><span data-stu-id="319c8-104">By default, this message is a warning.</span></span> <span data-ttu-id="319c8-105">警告を非表示にする方法や、警告をエラーとして扱う方法の詳細については、「 [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic)」をご覧ください。</span><span class="sxs-lookup"><span data-stu-id="319c8-105">For more information about hiding warnings or treating warnings as errors, see [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).</span></span>
  
 <span data-ttu-id="319c8-106">**エラー ID:** BC42031</span><span class="sxs-lookup"><span data-stu-id="319c8-106">**Error ID:** BC42031</span></span>  
  
## <a name="to-correct-this-error"></a><span data-ttu-id="319c8-107">このエラーを解決するには</span><span class="sxs-lookup"><span data-stu-id="319c8-107">To correct this error</span></span>  
  
- <span data-ttu-id="319c8-108">不要なステートメントを削除します。</span><span class="sxs-lookup"><span data-stu-id="319c8-108">Remove the redundant statement.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="319c8-109">関連項目</span><span class="sxs-lookup"><span data-stu-id="319c8-109">See also</span></span>

- [<span data-ttu-id="319c8-110">Try/catch ブロックを使用して例外をキャッチする方法</span><span class="sxs-lookup"><span data-stu-id="319c8-110">How to use the try/catch block to catch exceptions</span></span>](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [<span data-ttu-id="319c8-111">ユーザー フィルター例外ハンドラーの使用</span><span class="sxs-lookup"><span data-stu-id="319c8-111">Using User-Filtered Exception Handlers</span></span>](../../standard/exceptions/using-user-filtered-exception-handlers.md)
- [<span data-ttu-id="319c8-112">Try...Catch...Finally ステートメント</span><span class="sxs-lookup"><span data-stu-id="319c8-112">Try...Catch...Finally Statement</span></span>](../language-reference/statements/try-catch-finally-statement.md)
